version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:8080"      # host:container
    container_name: yeah-medication-frontend
    restart: unless-stopped
    read_only: true      # prevent writes to container FS
    tmpfs:
      - /var/run
      - /var/cache/nginx
    security_opt:
      - no-new-privileges:true
